# This workflow will perform the following steps for pushes the the develop branch
# * build the Schema and the Guidelines with Ant
# * publish the Schema to music-encoding/schema under ./dev
# * publish the Guidelines to music-encoding/guidelines under ./dev

name: Deploy Schema and Guidelines

on:
  workflow_dispatch: # trigger manually

env:
  # schema
  SCHEMA_REPO: ${{ github.repository_owner }}/schema
  SCHEMA_BRANCH: main

  # guidelines
  GUIDELINES_REPO: ${{ github.repository_owner }}/guidelines
  GUIDELINES_BRANCH: main

  # temporary directories
  SCHEMA_DIR: schema-dir
  GUIDELINES_DIR: guidelines-dir

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      ### BUIDLING THE SCHEMA AND THE GUIDELINES ###
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          # Whether to checkout submodules: `true` to checkout submodules or `recursive` to
          # recursively checkout submodules.
          #
          # When the `ssh-key` input is not provided, SSH URLs beginning with
          # `git@github.com:` are converted to HTTPS.
          #
          # Default: false
          submodules: recursive

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Ant
        # For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant
        run: |
          docker run --rm -v $(pwd):/data edirom/staticVerovioConverter:latest
