# This workflow will perform the following steps for pushes the the develop branch
# * build the Schema and the Guidelines with Ant
# * publish the Schema to music-encoding/schema under ./dev
# * publish the Guidelines to music-encoding/guidelines under ./dev

name: Deploy Schema and Guidelines

on:
  workflow_dispatch: # trigger manually

env:
  # schema
  SCHEMA_REPO: ${{ github.repository_owner }}/schema
  SCHEMA_BRANCH: main

  # test
  MUSIC-ENCODING_REPO : music-encoding/music-encoding
  MUSIC-ENCODING_BRANCH: develop
  MUSIC-ENCODING_DIR: test-dir

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      ### BUIDLING THE SCHEMA AND THE GUIDELINES ###
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          # Whether to checkout submodules: `true` to checkout submodules or `recursive` to
          # recursively checkout submodules.
          #
          # When the `ssh-key` input is not provided, SSH URLs beginning with
          # `git@github.com:` are converted to HTTPS.
          #
          # Default: false
          submodules: recursive


      - name: Checkout GUIDELINES_REPO into GUIDELINES_DIR
        uses: actions/checkout@v2
        with:
          # repository to check out
          repository: ${{ env.MUSIC-ENCODING_REPO }}
          # ref (branch, tag or SHA) to check out
          ref: ${{ env.MUSIC-ENCODING_BRANCH }}
          # relative path under $GITHUB_WORKSPACE to place the repository
          path: ${{ env.MUSIC-ENCODING_DIR }}

      - name: Verify
        run: | 
          pwd
          ls -R
          cd ${{ env.MUSIC-ENCODING_DIR }}/source/examples/verovio
          pwd
          ls -R

      - name: Build with Ant
        # For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant
        run: |
          docker run --rm -v ${{ env.MUSIC-ENCODING_DIR }}/source/examples/verovio:/data edirom/staticverovioconverter:latest
     
     
      - name: Verify
        run: |
          cd ${{ env.MUSIC-ENCODING_DIR }}/source/examples/verovio
          pwd
          ls -R
